# Generated by Django 4.1 on 2023-11-21 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rackapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rack",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="投稿日時",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rack",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
            preserve_default=False,
        ),
    ]
